---
title: "HW_4 - Exercise 3"
author: "Hugo"
date: "2023-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro_DS_HW4

#Exercice 3
```{r}
pckg <- c ('ggplot2','ggforce')

install.packages('ggforce')
#load several packages at once
lapply(pckg, require, character.only = TRUE)


gg_circles <- function(){
  
  # construction of the plot
  ggplot() + geom_circle(aes(x0 = 0, y0 = 0, r =200 ), fill = "grey", color = "grey") +
    geom_circle(aes(x0 = -300, y0 = 300, r = 20), fill = "red", color = "red") +
    geom_circle(aes(x0 = 0, y0 = -300, r = 20), fill = "blue", color = "blue") +
    geom_circle(aes(x0 = 300, y0 = 300, r = 20), fill = "green", color = "green") +
    geom_text(aes(x=100,y=-300,label ='Satellite 2'))+
    geom_text(aes(x=-210,y=300,label ='Satellite 1'))+
    geom_text(aes(x=210,y=300,label ='Satellite 3'))+
    geom_text(aes(x=-190,y=-200,label ='Flat Earth'))+
    # define graph boarders
    coord_cartesian(xlim = c(-350, 350), ylim = c(-350, 350)) +
    # name axis
    xlab("x") + ylab("y")
}

gg_circles()
```
```{r}
satellite_pos <- matrix(c(-300, 300, 0, 300, 300, -300), ncol=2, byrow=TRUE)

get_position <- function(d_est) {
  
  # Define the objective function to minimize
  objective <- function(theta) {
    sum((sqrt((satellite_pos[, 1] - theta[1])^2 + (satellite_pos[, 2] - theta[2])^2) - d_est + theta[3])^2)
  }
  
  # Use optim function to minimize objective function
  res <- optim(par = c(0, 0, 0), fn = objective, lower = c(-1000, -1000, -1000), upper = c(1000, 1000, 1000))
  
  # Define the gnss_position object
  gnss_pos <- list()
  gnss_pos$theta <- res$par
  gnss_pos$d_true <- sqrt((satellite_pos[, 1] - gnss_pos$theta[1])^2 + (satellite_pos[, 2] - gnss_pos$theta[2])^2)
  gnss_pos$epsilon <- d_est - gnss_pos$d_true
  
  class(gnss_pos) <- "gnss_position"
  return(gnss_pos)
}

# Example usage
d_est <- c(450, 450, 450)
pos <- get_position(d_est)
print(pos$theta)
print(pos$d_true)
print(pos$epsilon)
```