---
title: "HW4"
author: "Hugo"
date: "2023-05-03"
output: html_document
---

# Exercise 1
```{r}
library(leaflet)

m <- leaflet() %>% setView(lng = -0.887712, lat = 41.649693, zoom = 7)

#This is for the popups for each team
realMadrid <- paste(sep = "<br/>",
"<b> Real Madrid </b>",
"35",
"<b> Atletico Madrid </b>",
"11"
)

barcelona <- paste(sep  = "<br/>",
"<b> FC Barcelona </b>",
"26"
)

bilbao <- paste(sep = "<br/>",
"<b> Athletic Bilbao </b>",
"8"
)

valencia <- paste(sep = "<br/>",
"<b> Valencia </b>",
"6"
)

m %>% addTiles() %>% 
#Each team's circle is added, with the appropriate labelling, color, coordinates and size
addCircleMarkers(data = df, lat = 40.416775, lng = -3.703790, radius = 35) %>%

addCircleMarkers(data = df, lat = 41.390205, lng = 2.154007, radius = 26) %>%

addCircleMarkers(data = df, lat = 40.416775, lng = -3.703790, radius = 11) %>%

addCircleMarkers(data = df, lat = 43.263012, lng = -2.934985, radius = 8) %>%

addCircleMarkers(data = df, lat = 39.466667, lng = -0.375000, radius = 6) %>%
#We implement the popups to the specific location
addPopups(lat = 40.416775, lng = -3.703790, realMadrid, options = popupOptions(closeButton = FALSE)) %>%

addPopups(lat = 41.390205, lng = 2.154007, barcelona, options = popupOptions(closeButton = FALSE)) %>%

addPopups(lat = 43.263013, lng = -2.934985, bilbao, options = popupOptions(closeButton = FALSE)) %>%

addPopups(lat = 39.466667, lng = -0.375000, valencia, options = popupOptions(closeButton = FALSE))
```

# Exercise 2
```{r}
find_pi <- function(B = 5000, seed = 10, make_plot = TRUE) {
  # Control seed
  set.seed(seed)
  
  # Simulate B points
  point <- matrix(runif(2*B, -1, 1), B, 2)
  
  # Check if points are inside the circle
  inside <- rowSums(point^2) <= 1
  
  # Compute area of circle
  area_circle <- 4 * sum(inside) / B
  
  # Plot if desired
  if (make_plot) {
    plot(point[inside, 1], point[inside, 2], col = "cyan", pch = 16, cex = 0.5,
         xlim = c(-1.1, 1.1), ylim = c(-1.1, 1.1), xlab = "", ylab = "")
    points(point[!inside, 1], point[!inside, 2], col = "red", pch = 16, cex = 0.5)
    draw_circle <- function(center = c(0, 0), radius = 1) {
      theta <- seq(0, 2*pi, length.out = 100)
      lines(center[1] + radius * cos(theta), center[2] + radius * sin(theta), lwd = 2)
    }
    draw_circle(radius = 1)
    rect(-1, -1, 1, 1, lwd = 2)
  }
  
  # Return estimate of pi
  return(area_circle)
}
# Estimate pi with default arguments and plot
find_pi()
# Estimate pi with larger B and don't plot
find_pi(B = 100000, make_plot = FALSE)
```

# Exercise 3
```{r}
library(ggplot2)
get_position <- function(d1, d2, d3) {
  x <- c(-300, 300, 0)
  y <- c(300, 300, -300)
  d <- c(d1, d2, d3)
  
  f <- numeric(3) # function definie hors loop
  for (i in 1:3) {
    x0 <- x[i] - d[i] # algèbre fail 
    y0 <- y[i] - d[i] # algèbre fail 
    f[i] <- (x[i] - x0)^2 + (y[i] - y0)^2 - d[i]^2 # algèbre fail 
  }
  
  # Plot function 
  plot1<- ggplot() +
    geom_circle(aes(x0 = 0, y0 = 0, r = 200), fill = "grey", color = "grey") +
    geom_point(aes(x =x, y = y), shape = 23, color = "orange") +
    geom_circle(aes(x0 = -300, y0 = 300, r = 20), fill = "red", color = "red") +
    geom_circle(aes(x0 = 0, y0 = -300, r = 20), fill = "blue", color = "blue") +
    geom_circle(aes(x0 = 300, y0 = 300, r = 20), fill = "green", color = "green") +
    geom_text(aes(x = -250, y = 300, label ='Satellite 1')) +
    geom_text(aes(x = 300, y = 300, label ='Satellite 3')) +
    geom_text(aes(x = 10, y = -300, label ='Satellite 2')) +
    geom_text(aes(x = -190, y = -200, label ='Flat Earth')) +
    coord_cartesian(xlim = c(-400, 400), ylim = c(-400, 400)) +
    xlab("x") + ylab("y") + ggtitle("Position Estimation") +
    
    # display inputs on graph
    geom_text(aes(x = x[1], y = y[1] - 50, label = paste0("d1: ", round(d[1], 2))))+
    geom_text(aes(x = x[2], y = y[2] + 50, label = paste0("d2: ", round(d[2], 2))))+ 
    geom_text(aes(x = x[3], y = y[3] - 50, label = paste0("d3: ", round(d[3], 2))))
  
# Return summary and plot
return(list(summary(f),plot1))
}
get_position(453.2136,288.8427,418.3106)
```
